// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3-WIK7pT-CE43yR9QHtJ5k8W6W5rfu7g',
    appId: '1:1037946046685:web:89cb80a2b514ca6809b334',
    messagingSenderId: '1037946046685',
    projectId: 'todo-ad5f2',
    authDomain: 'todo-ad5f2.firebaseapp.com',
    storageBucket: 'todo-ad5f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIFqLwHFYyEOOVt9-z1FftiQoAlnr9ZIo',
    appId: '1:1037946046685:android:80cc67a1ff98123e09b334',
    messagingSenderId: '1037946046685',
    projectId: 'todo-ad5f2',
    storageBucket: 'todo-ad5f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBML6_Xpu8LTOBQl6q_NXrRHgOCmVBmtWM',
    appId: '1:1037946046685:ios:233fa66a68d591be09b334',
    messagingSenderId: '1037946046685',
    projectId: 'todo-ad5f2',
    storageBucket: 'todo-ad5f2.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBML6_Xpu8LTOBQl6q_NXrRHgOCmVBmtWM',
    appId: '1:1037946046685:ios:233fa66a68d591be09b334',
    messagingSenderId: '1037946046685',
    projectId: 'todo-ad5f2',
    storageBucket: 'todo-ad5f2.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3-WIK7pT-CE43yR9QHtJ5k8W6W5rfu7g',
    appId: '1:1037946046685:web:4b1fed3a0788c9d009b334',
    messagingSenderId: '1037946046685',
    projectId: 'todo-ad5f2',
    authDomain: 'todo-ad5f2.firebaseapp.com',
    storageBucket: 'todo-ad5f2.appspot.com',
  );
}
